### ISSUE TITLE
-f flag does not work in latest version

### ISSUE THREAD

**Issue by KatrinaHarris23** [cdeitrick/Lolipop#66]
-f and --frequencies both return the same error of "lolipop: error: unrecognized arguments"

**Comment by cdeitrick** [comment]
The algorithm used now is distinct from the original scripts which inspired this package, and the `--frequencies` option was removed since it was really only present to ensure compatibility with the original matlab scripts which is no longer possible. The `--similarity-cutoff` option replaces the functionality of the original `--frequencies` option by modifying the cutoff value used during the clustering step when inferring genotypes.
